data:
  data_root: "./data"                 # Root directory for data
  alignment_strength: 0.5            # Initial alignment strength
  num_neighbors: 10                  # Number of neighbors in data preprocessing

model:
  num_properties: 1                  # Number of input properties for the model
  num_layers: 3                      # Number of layers in the model
  hidden_dim: 16                    # Hidden dimension of the model layers

training:
  num_epochs: 100                     # Number of training epochs
  learning_rate: 0.001               # Learning rate for the optimizer
  loss_function: "mse_loss"           # Loss function to use (e.g., Mean Squared Error)

analysis:
  name: "basic_experiment"           # Name of the analysis/experiment
  output_dir: "./output"             # Output directory for the analysis

experiments:
  run_basic_experiment: true
  run_datascaling_experiment: false
  run_observables_experiment: false
  run_distances_experiment: false