data:
  data_root: "./data"                # Root directory for data
  alignment_strength: 0.5            # Initial alignment strength
  num_neighbors: 10                  # Number of neighbors in data preprocessing
  batch_size: 1024                     # Batch size for training

model:
  num_properties: 1                       # Number of input properties for the model
  egnn_num_layers: 3                      # Number of layers in the model
  egnn_hidden_dim: 16                     # Hidden dimension of the model layers
  vmdn_hidden_layers: [32, 32]            # Hidden layers of the VMDN model
  vmdn_regularization: 0.0              # Regularization parameter for the VMDN model
  vmdn_dropout: 0.0                       # Dropout rate for the model

training:
  pretrain: true
  pretrain_epochs: 10
  pretrain_learning_rate: 0.001
  train_epochs: 10
  train_learning_rate: 0.001

analysis:
  name: "basic_experiment"           # Name of the analysis/experiment
  output_dir: "./output"             # Output directory for the analysis

experiments:
  run_basic_experiment: true
  run_datascaling_experiment: false
  run_observables_experiment: false
  run_distances_experiment: false